# Generated by Django 6.0.3 on 2026-03-11 22:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0002_alter_user_organization_alter_user_role_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='organization',
            name='logo',
            field=models.FileField(blank=True, null=True, upload_to='organization_logos/'),
        ),
    ]
